services:
  - type: web
    name: furniture-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn furniture.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_VRhQfcs63AOZ@ep-tiny-cherry-aitahnof-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: RENDER_EXTERNAL_URL
        value: https://furniture-backend-gfjq.onrender.com
      - key: FRONTEND_URL
        value: https://furniture1-pied.vercel.app
