services:
  - type: web
    name: furniture-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn furniture.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
