services:
  - type: web
    name: furniture-backend
    runtime: python
    plan: free
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python manage.py migrate && gunicorn furniture.wsgi
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: django-prod-9mX3Qv7Lk2Nf8Tz4Rw1Yp6Ha0Bc5De7J
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_VRhQfcs63AOZ@ep-tiny-cherry-aitahnof-pooler.c-4.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - key: RENDER_EXTERNAL_URL
        value: https://furniture-backend-gfjq.onrender.com
      - key: FRONTEND_URL
        value: https://furniture1-pied.vercel.app
      - key: ALLOWED_HOSTS
        value: furniture-backend-gfjq.onrender.com
